name: Tests

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  pytest:
    name: PyTest

    strategy:
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9', 'pypy-3.7' ]
        exclude:
          - os: macos-latest
            python-version: 'pypy-3.7'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v4

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ matrix.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('pyproject.toml') }}

      - run: sudo apt-get install -y libxml2-dev libxslt-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: poetry install -E client_id -E filelike

      - run: poetry run pytest
        env:
          TIDAL_APK_URL: ${{ secrets.TIDAL_NONDASH_APK_URL }}
          TIDAL_CLIENT_ID: ${{ secrets.TIDAL_NONDASH_CLIENT_ID }}
          TIDAL_REFRESH_TOKEN: ${{ secrets.TIDAL_NONDASH_REFRESH_TOKEN }}
